name: "CI setup"
description: "Runs base CI"
runs:
  using: "composite"
  steps:
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install Dependencies
      run: yarn
      shell: bash
